### ISSUE TITLE
On the product selector, the urls that link to the signup app need to include the offerId, and they need to all point to `/signup` instead of `/signup/premium` etc

### ISSUE THREAD

**Issue by ifyio** [Financial-Times/next-signup#118]
SO instead of 

`https://next.ft.com/signup/premium?term=annual&segID=400864&segmentID=1ee18acf-9ef8-4f19-57a0-df24a75a0411` 

... we want 

`https://next.ft.com/signup?offerID=713f1e28-0bc5-8261-f1e6-eebab6f7600e&term=annual&segID=400864&segmentID=1ee18acf-9ef8-4f19-57a0-df24a75a0411`.

![image](https://cloud.githubusercontent.com/assets/675909/12887802/9adeaaee-ce6e-11e5-9539-399d0e7e6e6f.png)

The offer id can be taken from the data that comes back from the barrier api

**Comment by TheoLeanse** [comment]
Have spoken to Fahad from membership about changing the `callToActionUrl` served from the Barriers API

**Comment by TheoLeanse** [comment]
Barriers API changes went live yesterday, and that's accommodated in this PR on the product selector app:

https://github.com/Financial-Times/next-product-selector/pull/53
