### ISSUE TITLE
Remove the following routes as they will no longer be needed

### ISSUE THREAD

**Issue by ifyio** [Financial-Times/next-signup#120]
The routes that should be removed are 

- /signup/standard
- /signup/premium

The only route that should remain is the `/signup` route. This route should not be removed from the app. 

The routes should be removed from the following:

- The app: https://github.com/Financial-Times/next-signup/blob/master/server/init.js#L17-L18
- The service registry: http://git.svc.ft.com/projects/NEXT/repos/service-registry/browse/models/profiles.js#821-822

**Comment by ifyio** [comment]
@lc512k this is a good one for you to look at as it will allow you to familiarise yourself (at least a little bit) with the service registry. If you do get to it, grab me if you need help.

**Comment by lc512k** [comment]
Thanks @ifyio. On it.

**Comment by lc512k** [comment]
https://github.com/Financial-Times/next-signup/pull/123
