### ISSUE TITLE
Add error state for terms and conditions checkbox

### ISSUE THREAD

**Issue by ifyio** [Financial-Times/next-signup#145]
The text should just go red and the error message be shown at the bottom of it similar to the rest of fields

**Comment by tgabe** [comment]
Can we also add * (asterisk character) to the field so that it's marked as a required field?

**Comment by lc512k** [comment]
Fixed in https://github.com/Financial-Times/next-signup/pull/244
Using origami standards for checkbox error state:
http://origami-buildservice-qa.herokuapp.com/v2/demos/o-forms@2.0.0/checkboxes
