### ISSUE TITLE
Implement funnel tracking for the signup process

### ISSUE THREAD

**Issue by ifyio** [Financial-Times/next-signup#170]
An event should be sent to spoor when when various actions and failures occur throughout the signup process. So for instance, when a user account is created or when the creation fails, the event should be dispatched.

**Comment by commuterjoy** [comment]
Send an event to spoor (probably from the server) ...

https://github.com/Financial-Times/next-preflight/blob/master/server/utils/spoor-api.js

I think `category: signup` and the actions things like `account-created`, `subscribed` and include failure events too - Eg, `payment-failure`. And make sure you include as much meta-data of things like the offer id, payment gateway region, and pass on the user's cookie in the headers ...

Later you might want to add some server side CTA events around form fields with o-tracking.

**Comment by commuterjoy** [comment]
Once we have these events we can build arbitrary funnels, which means analysts and product teams can just pick out the key events in that journey and model them as funnels, conversation rates or whatever.

Over time teams will add more events - account upgrades, marketing emails etc. - so it becomes simple to build conversion rates of longer-term events (Eg, conversion rate of trialist).

**Comment by adambraimbridge** [comment]
@ifyio I'm keen to see some funnels in beacon. Hit me up if I can be of any help.
