### ISSUE TITLE
Check if the password validation rules are correct. It seems to be not allowing special characters.

### ISSUE THREAD

**Issue by ifyio** [Financial-Times/next-signup#191]

**Comment by lc512k** [comment]
This is what we have, so no special chars allowed
`const pattern = /^[A-Za-z0-9\\-]+$/;`
@ifyio I remember copying this from that spreadsheet with rules for the form, but can't find it atm. Should we add special characters then?

**Comment by ifyio** [comment]
Ahh ok. I guess thats fie then as thats the behaviour on the current form. Plus we also state that only numbers and letters are allowed so I will just close this issue.

**Comment by lc512k** [comment]
Oh ok. I made this pull request just in case https://github.com/Financial-Times/next-signup/pull/217 We can close that too if we don't want special chars. If the APIs involved are ok with these characters, there's probably no harm in having them
