### ISSUE TITLE
offerId parameter value has no effect

### ISSUE THREAD

**Issue by tgabe** [Financial-Times/next-signup#227]
Using the Standard offer ID on the signup URL has no effect: https://next.ft.com/signup/?offerId=c8ad55e6-ba74-fea0-f9da-a4546ae2ee23&term=annual&segID=400864&segmentID=1ee18acf-9ef8-4f19-57a0-df24a75a0411

Premium sign-up offer is currently being returned all the time

**Comment by lc512k** [comment]
Yes, the offerId is hardcoded at the moment for the demo. We'll be taking that out today.
