### ISSUE TITLE
Country/Geo location not picked up

### ISSUE THREAD

**Issue by tgabe** [Financial-Times/next-signup#229]
Using a VPN and confirming the geolocation details passed in the request, the signup form doesn't pick up the values and is setting the Country field as "United Kingdom" by default.

Screenshots of response headers below:
![screen shot 2016-03-04 at 14 26 01](https://cloud.githubusercontent.com/assets/14106759/13529709/733b72b4-e215-11e5-9f18-0631f1034907.png)

![screen shot 2016-03-04 at 14 27 34](https://cloud.githubusercontent.com/assets/14106759/13529720/7ae36ac6-e215-11e5-800f-89401f8e4c10.png)

**Comment by lc512k** [comment]
Solved
