### ISSUE TITLE
Look into issues like these https://app.getsentry.com/nextftcom/ft-next-signup/issues/115589819/

### ISSUE THREAD

**Issue by ifyio** [Financial-Times/next-signup#252]
I think that api urls have to be registered somewhere for metrics to be setup

**Comment by lc512k** [comment]
User API is set up but not offer
https://github.com/Financial-Times/next-metrics/blob/master/lib/metrics/services.js
Working on it now

**Comment by lc512k** [comment]
https://github.com/Financial-Times/next-metrics/pull/83/files
