### ISSUE TITLE
Update card type images with both colour and faint images

### ISSUE THREAD

**Issue by ifyio** [Financial-Times/next-signup#257]
![amex-colour](https://cloud.githubusercontent.com/assets/675909/13601288/da381a8a-e526-11e5-9753-ba23f625de5f.png)
![amex-grey](https://cloud.githubusercontent.com/assets/675909/13601298/e663d93e-e526-11e5-9288-a70110d16ad6.png)
![mcard-colour](https://cloud.githubusercontent.com/assets/675909/13601300/eda8aa08-e526-11e5-9bdb-2f886260740a.png)
![mcard-grey](https://cloud.githubusercontent.com/assets/675909/13601307/f61a2e28-e526-11e5-88c1-b8544586629e.png)
![visa-colour](https://cloud.githubusercontent.com/assets/675909/13601317/0875b36c-e527-11e5-9086-fc4f8b376e54.png)
![visa-grey](https://cloud.githubusercontent.com/assets/675909/13601320/105161a8-e527-11e5-9ca3-9239d221d616.png)

**Comment by lc512k** [comment]
https://github.com/Financial-Times/next-signup/pull/457
