### ISSUE TITLE
Handle country change (polished)

### ISSUE THREAD

**Issue by lc512k** [Financial-Times/next-signup#281]
Improve on https://github.com/Financial-Times/next-signup/issues/275 by using the offer api to get the new price/currency/symbol

**Comment by lc512k** [comment]
@Purvi22Patel this issue is the polished version: showing the exact currency and symbol. I'll update our current message with "Currency has been updated to reflect the change you have made to Country"

**Comment by Purvi22Patel** [comment]
@lc512k thanks for confirming and making the change to the message.

**Comment by lc512k** [comment]
Has been implemented already for minimum mvp
