### ISSUE TITLE
Cant toggle between Payment options in HTC 1 MiniX UC Browser

### ISSUE THREAD

**Issue by bushraawan** [Financial-Times/next-signup#290]
Iphone4 Safari, BB10 and IE11You can not toggle between the monthly and annual payment options.

**Comment by lc512k** [comment]
previously raised as https://github.com/Financial-Times/next-signup/issues/211

**Comment by lc512k** [comment]
Tested and working on iOS7. @bushraawan, can we confirm on the other platforms where it was failing? If it works there we can go ahead and close this issue

**Comment by bushraawan** [comment]
Tested on BB10, iOS7 and IE browsers, Works now.

**Comment by bushraawan** [comment]
Happening on HTC 1 MiniX UC Browser

**Comment by lc512k** [comment]
joining with https://github.com/Financial-Times/next-signup/issues/389
