### ISSUE TITLE
Usage of "terms and policies" in T&Cs validation message

### ISSUE THREAD

**Issue by tgabe** [Financial-Times/next-signup#296]
![screen shot 2016-03-10 at 18 00 46](https://cloud.githubusercontent.com/assets/14106759/13679235/b1401d42-e6ea-11e5-8dde-6d608e99bd42.png)

FT.com uses "Please accept our terms & conditions". @Purvi22Patel is double-checking this with Legal team.

**Comment by lc512k** [comment]
Updated to "Please accept our terms & conditions".

@Purvi22Patel please reopen if copy changes after talking to legal and we'll update again.

**Comment by tgabe** [comment]
The text (1 sentence in particular) changes depending on the subscription type (Trial or Premium/Standard) and the payment frequency (monthly or annual).
