### ISSUE TITLE
Validation message for > 15 char in Phone Number field

### ISSUE THREAD

**Issue by tgabe** [Financial-Times/next-signup#297]
![screen shot 2016-03-10 at 18 10 39](https://cloud.githubusercontent.com/assets/14106759/13679407/88e50c08-e6eb-11e5-966b-40e7e8f64b93.png)

Validation message does not match the error state

**Comment by tgabe** [comment]
Low priority = Polished MVP or Ideal solution milestone?

**Comment by lc512k** [comment]
fixed
