### ISSUE TITLE
Terms & Conditions - copy 

### ISSUE THREAD

**Issue by Purvi22Patel** [Financial-Times/next-signup#298]
Terms and Conditions 
 
[  ] I confirm I have read and agree to the terms & conditions, privacy policy and cookie policy. 
 
Your subscription lasts for  a year.  To give you uninterrupted access we will automatically renew it using the payment method you provided, unless you cancel before your renewal date.  We will send you a reminder of this date in advance. 
 
Find out more about our cancellation policy in our terms & conditions.

----------
(Marketing consent section)
 
We will send you occasional emails to improve your experience of the Financial Times.  

By submitting this form, you indicate your consent to also being contacted by Financial Times by email, post or phone about our other products, services or special offers unless you untick this box. [✓]

You can change your preferences anytime in the My Account section. 

[Complete Purchase & Buy]

[  ] Indicates an empty box.
[✓] Indicates a pre-ticked box.
[Complete Purchase & Buy] Indicates a button containing the words 'Complete Purchase & Buy'

**Comment by lc512k** [comment]
Updated in https://github.com/Financial-Times/next-signup/pull/299

The second checkbox remains left-aligned since the origami component we use won't work out of the box if we right-align it. We can look into updating this for the polished version or beyond if needed.

**Comment by lc512k** [comment]
@Purvi22Patel @tgabe reverting to what we had before, as this longer version requires changing the text dynamically per subscription type. Moving over to Polished MVP milestone.

**Comment by lc512k** [comment]
done

**Comment by Purvi22Patel** [comment]
@lc512k can you change the CTA to "Buy"
