### ISSUE TITLE
Safari iOS7/IE/BB 10 - submitting the form redirects to PSP

### ISSUE THREAD

**Issue by bushraawan** [Financial-Times/next-signup#301]
On Iphone4, when a user tries to submit the form by filling some of the fields, it redirects to PSP.

**Comment by lc512k** [comment]
discussed with @bushraawan, we will have more information on devices/OS to reproduce this bug

**Comment by tgabe** [comment]
Renamed the title of the bug to reflect that actual browser. Here's a curl request that gets a 302 response to the PSP page: curl -H "Host: next.ft.com" -H "Referer: https://next.ft.com/signup/?offerId=713f1e28-0bc5-8261-f1e6-eebab6f7600e&term=annual&segID=400864&segmentID=1ee18acf-9ef8-4f19-57a0-df24a75a0411" -H "Proxy-Connection: keep-alive" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" -H "Cookie: _chartbeat2=BaMy3jBrcEfCCTDisV.1447696228530.1449234562362.0000000000000001; __gads=ID=d761f99fe51deca5:T=1409227222:S=ALNI_MbLGw-7Wocj9pRoRN3m3ZyjJZmKJg; __utma=138983524.1282616214.1409227093.1420806920.1426855582.4; _ga=GA1.2.1282616214.1409227093; _gat=1; anon-opt-in=true; AYSC=_01_02X_04PVT_05_06_07_12SL60LT_13GBR_14GBR_15GB_17PVT_18PVT_19xxxx_20x_22ToolsP0P2_24PVT_25PVT_26PVT_27PVT_40_41_42_45_47_53_96PVT_97c_98PVT_; AYSC_C=S; FT_M=D=A|F=|R=0; FT_SITE=NEXT; FTAllocation=-; FTUserTrack=92.40.250.93.1409227104186693; h2_rtt=2; h2_spd=5000; mm_pc=Discount%3DNo%26MarketoEmail%3DNoMarketoEmail%26B2BorB2C%3DB2C; mmcore.pd=1132802556%7CHQAAAApUi+8M7AoAAA%3D%3D; mmcore.srv=ldnvwcgeu12; mmcore.tst=0.252; mmid=1132802556%7CHQAAAApUi+8M7AoAAA%3D%3D; next-flags=nextSubscriptionApp%3Aon; o-tracking-proper-id=d8088a84-cf43-4f8e-8486-ca11529d589e; SIVISITOR=MS4zOTYuMTM5NDM1OTM1NzY1NS4xNDA5MjI3MDkwOTQwLjRhYzkzOTNj*; spoor-id=d8088a84-cf43-4f8e-8486-ca11529d589e" -H "Accept-Language: en-gb" -H "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 7_1_2 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D257 Safari/9537.53" --compressed https://next.ft.com/signup/?offerId=713f1e28-0bc5-8261-f1e6-eebab6f7600e&currencyCode=GBP&email=&password=&firstName=&lastName=&phoneNumber=&billingCountry=GBR&zipCode=&optInToMarketing=true

**Comment by lc512k** [comment]
@tgabe thanks! Is this using a prod offerId?

**Comment by bushraawan** [comment]
Also BB10 is redirecting to the PSP page

**Comment by tgabe** [comment]
Yes. This also happens in IE desktops - 9, 10 and 11. Bushra confirmed it's the same for BB 10.

**Comment by bushraawan** [comment]
HTC 1 Mini X too

**Comment by tgabe** [comment]
This issue doesn't appear in the IE browsers anymore. We'll check on the mobile browsers on Monday.
