### ISSUE TITLE
Order for payment options is not the same in Standard and Premium sign-up pages

### ISSUE THREAD

**Issue by tgabe** [Financial-Times/next-signup#310]
Premium - yearly option is on the left and it's selected by default
Standard - monthly option is on the left and it's selected by default

The "term" we pass on to the URL uses "annual". So we should select "yearly" option by default. As for the exact order, maybe ask Clem or Purvi.

**Comment by lc512k** [comment]
If annual is passed as a query param we preselect it now on the form, whether it's on the right or the left. As for the order, the app will display it in the order passed in the API response (both responses should ideally be the same for standard and premium).

**Comment by lc512k** [comment]
https://github.com/Financial-Times/next-signup/pull/466

**Comment by tgabe** [comment]
Standard subscription still has yearly option on the right: 
![screen shot 2016-04-14 at 10 22 52](https://cloud.githubusercontent.com/assets/14106759/14523326/f58537d4-022a-11e6-92f7-7363d706e964.png)

**Comment by lc512k** [comment]
@saldixon @tgabe the offer api returns monthly first and yearly second for standard and viceversa for premium. If we can have those payloads be the same for both (yearly first) it'll show up as we want it.

**Comment by tgabe** [comment]
Moving this to Jira since this closed: https://jira.ft.com/browse/NFT-423. This isn't a priority for the 2nd milestone, btw.
