### ISSUE TITLE
No CC form, zip code field and no currency change message in IE  and Edge browsers

### ISSUE THREAD

**Issue by tgabe** [Financial-Times/next-signup#311]
Issue present in IE 9, 10 and 11

<img width="386" alt="screen shot 2016-03-11 at 18 33 10" src="https://cloud.githubusercontent.com/assets/14106759/13711952/09d5f6e2-e7b9-11e5-8846-1f1b2a92c210.png">

**Comment by tgabe** [comment]
Added MS Edge to the list

**Comment by lc512k** [comment]
Need to find alternative solution to pointer-events
http://caniuse.com/#feat=pointer-events

**Comment by Purvi22Patel** [comment]
@lc512k @ifyio @tgabe I've moved this to MVP - IE8 is the 2nd most used browser for both Next & FT.com. Edge is  the 8th most used. 
Zipcode is a Zurora req?

**Comment by lc512k** [comment]
This issue doesnt affect IE8, as that browser gets a different page, not
the form.

Zip code is a zuora req for USA and Canada.

**Comment by tgabe** [comment]
I think @Purvi22Patel meant IE 11 (not IE 8) based on the Feb 2016 stats - https://drive.google.com/a/ft.com/file/d/0BzJVn8HvTbSXTG9LVEJFLWJFS3M/view

**Comment by lc512k** [comment]
Fixed. https://github.com/Financial-Times/next-signup/pull/318
