### ISSUE TITLE
Confirmation page issues

### ISSUE THREAD

**Issue by bushraawan** [Financial-Times/next-signup#324]
Please see the screenshot
![confirmationpage](https://cloud.githubusercontent.com/assets/17766241/13776773/e03ad404-eaa3-11e5-9d8b-52b9b6511ce2.jpg)

**Comment by Purvi22Patel** [comment]
@ifyio for MVP can we remove "as well as" from the product description until we add the rest of the description (from the bullet List) so it reads ok.

**Comment by ifyio** [comment]
Removed the 'as well as ' copy.

**Comment by ifyio** [comment]
Moving this to the polished MVP milestone
