### ISSUE TITLE
Confirmation Page: Renewal Date looks wrong

### ISSUE THREAD

**Issue by bushraawan** [Financial-Times/next-signup#327]
The Renewal Date on confirmation/Thankyou page looks wrong. Customer has purchased a Trial Subscription on 15/03/2016 but Renewal Date appears as 26/01/17

**Comment by commuterjoy** [comment]
This doesn't stop a subscription does it?

**Comment by saldixon** [comment]
no, but is there a Legal consideration to telling customer the wrong renewal date?

**Comment by Purvi22Patel** [comment]
This one has be correct

**Comment by lc512k** [comment]
@bushraawan, I can no longer reproduce a case where we'd have an empty renewal date. I've moved this to the polished MVP milestone for now.

**Comment by lc512k** [comment]
https://github.com/Financial-Times/next-signup/pull/367

**Comment by bushraawan** [comment]
This cant be closed, the date looks still wrong on the thankyou page.
![thankyoudate](https://cloud.githubusercontent.com/assets/17766241/13880039/5aca0ab2-ed12-11e5-8c38-3842bb225a73.jpg)
![renewal date email](https://cloud.githubusercontent.com/assets/17766241/13880048/61ccf4f0-ed12-11e5-99f5-11a1f397c178.jpg)

**Comment by lc512k** [comment]
@bushraawan this solved the issue of the date being empty. So it's off by 3 days every time?

**Comment by bushraawan** [comment]
But the issue i reported was of a wrong date not an empty date?

**Comment by lc512k** [comment]
@bushraawan what's the expected date? We currently add 1 month to the creation date

**Comment by bushraawan** [comment]
for Trial is 4 weeks=28 days

and for payment process

if its CC it will be exactly +1 month (other Subscriptions) 

for DD its 1 month +3 days (other subscriptions)

**Comment by lc512k** [comment]
Resolved
