### ISSUE TITLE
When there's a payment failure, signup page refreshes with no credit card form

### ISSUE THREAD

**Issue by tgabe** [Financial-Times/next-signup#332]
To get to the form, the user needs to select another credit card type and then select the original one again.

![image](https://cloud.githubusercontent.com/assets/14106759/13779685/2c9b33ba-eab4-11e5-8b93-c3afcd73e5dd.png)

**Comment by commuterjoy** [comment]
users can surely fix this themselves, albeit it in a sub-optimal way
