### ISSUE TITLE
Update Product Description copy for all products in Form

### ISSUE THREAD

**Issue by Purvi22Patel** [Financial-Times/next-signup#338]
Standard: Access to FT’s trusted content on your desktop, mobile and tablet, to help you navigate through today’s complex business landscape.

Premium: Unlimited access to FT articles, tools and features, email briefings, ePaper, and exclusive content on FT.com, to help you navigate through today’s complex business landscape.

Trial - Relabel to "Digital Trial"  
4 weeks of unlimited access to FT articles, tools and features, email briefings, ePaper, and exclusive content on FT.com, to help you navigate through today’s complex business landscape. 

https://docs.google.com/a/ft.com/presentation/d/1LUViT5SPjkpzRf4dXn-vHllmtzpoipcrMUZRkc1zOQI/edit?usp=sharing

**Comment by lc512k** [comment]
done
