### ISSUE TITLE
Confirmation Email for Weekend offer

### ISSUE THREAD

**Issue by bushraawan** [Financial-Times/next-signup#341]
The confirmation email for weekend offer, does not display the features.
![weekend](https://cloud.githubusercontent.com/assets/17766241/13785376/3c32a404-eacb-11e5-823b-8a066c5c981c.jpg)

**Comment by commuterjoy** [comment]
i think this is fixed in the code, might need deploying.

**Comment by bushraawan** [comment]
fixed! and verified
