### ISSUE TITLE
Android Stock Browser Card Number field doesnt have spaces in number

### ISSUE THREAD

**Issue by bushraawan** [Financial-Times/next-signup#350]
On Android 4.4 Stock Browser when user enters the card number, it doesnt have spaces
![screenshot_2016-03-16-14-16-07](https://cloud.githubusercontent.com/assets/17766241/13815300/fe8c4792-eb81-11e5-9fb6-10791dce8f6c.png)

**Comment by lc512k** [comment]
@bushraawan @tgabe I'm not certain we can modify this, as it's handled by zuora, also it's more a cosmetic discrepancy with other platforms, rather than an actual issue. Please update if it's actually causing problems.

**Comment by bushraawan** [comment]
It gets difficult for the user to record if he has entered 16 digits or not, its just for the user-friendliness.
