### ISSUE TITLE
Dashboards

### ISSUE THREAD

**Issue by lc512k** [Financial-Times/next-signup#368]
Add some dashboards in the new beacon

ETA: Number of visits from paywall - number of subscriptions

**Comment by Purvi22Patel** [comment]
@lc512k we should raise this as a card for the backlog.

**Comment by lc512k** [comment]
Starting point https://beacon.ft.com/dashboard/signup/
To add more dashboards, edit this file
https://github.com/Financial-Times/next-beacon-v2/blob/master/dashboards/signup.yml
