### ISSUE TITLE
User details are exposed in the query string of the thankyou page (Security issue?)

### ISSUE THREAD

**Issue by ifyio** [Financial-Times/next-signup#374]

**Comment by commuterjoy** [comment]
Disagree

**Comment by Purvi22Patel** [comment]
My understanding is, it's a security risk as we are displaying the users email address in the URL. If we don't display then it's fine.

**Comment by lc512k** [comment]
Pretty sure this is quite safe over HTTPS, though we could look to POST these params instead in the future for a cleaner URL, but definitely not a show stopper, imo.

**Comment by commuterjoy** [comment]
Yup, agree with @lc512k

**Comment by lc512k** [comment]
solved by https://github.com/Financial-Times/next-signup/pull/403

**Comment by lc512k** [comment]
@commuterjoy @ifyio I've rolled back to before turning switch to a POST from a GET for the thank you page, effectively making this an issue again until we redeploy the up-to-date master

GETting the thank you page works fine. POSTing to it works fine locally, but in prod times out. I've increased the timeout in both our code and the router to 10000, but it persists, so I've rolled back to `v231` have a working form over the long weekend.

**Comment by lc512k** [comment]
production is back on master branch

**Comment by ifyio** [comment]
@lc512k I think you will need to add the page url to https://github.com/Financial-Times/next-cdn/blob/807d579095c468deccd49d9cb1a7df05f8f0d4f5/src/vcl/preflight.vcl#L135 to allow posts to work.

**Comment by lc512k** [comment]
@ifyio https://github.com/Financial-Times/next-cdn/pull/16/files?
