### ISSUE TITLE
Can't toggle between Monthly and Annual Option

### ISSUE THREAD

**Issue by bushraawan** [Financial-Times/next-signup#389]
- [x] Windows FF 45.0.1
- [x] HTC 1 MiniX UC 
- [x] ?

**Comment by lc512k** [comment]
@bushraawan @tgabe can we compile a list of browser/device combinations where the toggle fails  to update the above, please? It would help to also estimate the % of users potentially affected

**Comment by tgabe** [comment]
I would focus on just the Firefox desktop browser. We've got a low usage for UC Browser - we've got all sorts of issues with that browser across the entire Next site.

**Comment by lc512k** [comment]
Thanks, @tgabe. Re FF Is it that one specific version or does the toggle simply not work on FF at all?

**Comment by tgabe** [comment]
Issue appears at both v44 and v45 regardless of OS version. These versions are latest version and latest-1. For Firefox and Chrome, we assume users have the latest or latest-1 versions.
