### ISSUE TITLE
User details exposed in query string of re-rendered signup page when signup attempt fails

### ISSUE THREAD

**Issue by saldixon** [Financial-Times/next-signup#397]
Security issue.  3rd party scripts cannot be added to this page until this issue is fixed.

**Comment by lc512k** [comment]
same as https://github.com/Financial-Times/next-signup/issues/374?

**Comment by Purvi22Patel** [comment]
@commuterjoy will this be a blocker for DFA tagging?

**Comment by commuterjoy** [comment]
@Purvi22Patel not sure - i need to see what DFA is doing

**Comment by lc512k** [comment]
The issue of exposing the user details in the query param is solved in https://github.com/Financial-Times/next-signup/issues/374. cc @saldixon

**Comment by tgabe** [comment]
The user details are not shown anymore in the URL when there is a payment failure on the signup page.

**Comment by Purvi22Patel** [comment]
Yey! Thanks everyone for your efforts :)
