### ISSUE TITLE
On submitting the form, the form keeps showing the loader

### ISSUE THREAD

**Issue by bushraawan** [Financial-Times/next-signup#405]
While submitting a form, the loader is constantly shown and the confirmation email is received.

This might be because Subs-API being slow to response.
![loadererror](https://cloud.githubusercontent.com/assets/17766241/14015169/0f52d572-f1af-11e5-97ee-598a99385bcd.jpg)

**Comment by bushraawan** [comment]
![loaderlogs](https://cloud.githubusercontent.com/assets/17766241/14015225/7132950c-f1af-11e5-83fe-9eae2053cfdb.jpg)

**Comment by commuterjoy** [comment]
hmm, we are giving it 10 seconds to respond, but the slowness has proven a problem in the past :/

**Comment by lc512k** [comment]
do as:
https://github.com/Financial-Times/next-cdn/commit/1039b6a6294a86f58819ee646cbbd66d7273bda0
to keep from losing the POST body in preflight

make change, `make deploy-stage` and test in `https://next-staging.ft.com/` before deploying cdn to prod

**Comment by lc512k** [comment]
https://github.com/Financial-Times/next-cdn/pull/16

**Comment by lc512k** [comment]
@bushraawan fixed
