### ISSUE TITLE
Zuora / TLS issue

### ISSUE THREAD

**Issue by ifyio** [Financial-Times/next-signup#421]
@commuterjoy  said

> Please see the update below. In a nutshell, Zuora are planning to disable TLS 1.0 for inbound connections in order to continue to maintain security standards and will therefore only support versions 1.1 and above. The date we've been given for this change to be made is next week (7th April).
> 
> Over the past day or so, we have been extensively testing across a number of VM's and Native Browsers and we've uncovered consistent issues where TLS 1.0 is not supported as part of the default settings for IE8, 9 and 10. IE11 appears to work fine.
> 
> Impact: This means, any users who are trying to sign-up using the B2C signup form and are using lower versions of IE (specifically 8, 9 & 10), may not have this setting enabled by default and will therefore be unable to subscribe successfully. There may also be an impact to MMA and this is likely to also impact Next.
> 
> Next steps: As we're unable to force these updates ourselves onto users browsers, we will have to look at a way to identify these cases and put some special messaging in place for end users to either ask for them to update their browsers or contact Customer Services. This all needs to be implemented by next Thursday, so the Commerce team will be picking this up as a top priority.

**Comment by commuterjoy** [comment]
http://community.zuora.com/t5/Zuora-Announcements/Action-Required-Zuora-is-Disabling-TLS-1-0/ba-p/2177

**Comment by commuterjoy** [comment]
Not sure how much of a priority this is TBH, I'd have a chat to Sarandeep first

**Comment by lc512k** [comment]
https://github.com/Financial-Times/next-signup/pull/423

**Comment by lc512k** [comment]
Relates to https://github.com/Financial-Times/next-signup/issues/262
