### ISSUE TITLE
Align TLS messaging with the following

### ISSUE THREAD

**Issue by ifyio** [Financial-Times/next-signup#445]
Purvi said...

> Ania is working on the  TLS  message for FT.com. We should adopt this wording for consistency (provided we can support those browsers) and apply the following tweaks: 1. remove the opera logo. 2. instead of Choose one of the browsers below:" to "We recommend one of the browsers below:"?

![image](https://cloud.githubusercontent.com/assets/675909/14346620/ebc0583a-fcaa-11e5-8e6b-f9b056cd0554.png)

**Comment by tavvy** [comment]
This has been completed.
